# Generated by Django 4.2.4 on 2023-08-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('birth_year', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_day', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('memo', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
    ]
